//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThTest.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShareResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShareResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThTest.Resources.ShareResource", typeof(ShareResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        internal static string RequiredUsername {
            get {
                return ResourceManager.GetString("RequiredUsername", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ConfirmPasswordNotMatch is required..
        /// </summary>
        internal static string ConfirmPasswordNotMatch
        {
            get
            {
                return ResourceManager.GetString("ConfirmPasswordNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RequiredConfirmPassword is required..
        /// </summary>
        internal static string RequiredConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("RequiredConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RequiredEmail is required..
        /// </summary>
        internal static string RequiredEmail
        {
            get
            {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RequiredEmail is required..
        /// </summary>
        internal static string RequiredFullname
        {
            get
            {
                return ResourceManager.GetString("RequiredFullname", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PasswordInvalid is required..
        /// </summary>
        internal static string PasswordInvalid
        {
            get
            {
                return ResourceManager.GetString("PasswordInvalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to RequiredProductName is required..
        /// </summary>
        internal static string RequiredProductName
        {
            get
            {
                return ResourceManager.GetString("RequiredProductName", resourceCulture);
            }
        }

        internal static string MaxLengthProductName
        {
            get
            {
                return ResourceManager.GetString("MaxLengthProductName", resourceCulture);
            }
        }

        internal static string RequiredUnitPrice
        {
            get
            {
                return ResourceManager.GetString("RequiredUnitPrice", resourceCulture);
            }
        }

        internal static string RangeUnitPrice
        {
            get
            {
                return ResourceManager.GetString("RangeUnitPrice", resourceCulture);
            }
        }

        internal static string MaxLengthProductDescription
        {
            get
            {
                return ResourceManager.GetString("MaxLengthProductDescription", resourceCulture);
            }
        }

        internal static string RequiredCategory
        {
            get
            {
                return ResourceManager.GetString("RequiredCategory", resourceCulture);
            }
        }

        internal static string RequiredSupplier
        {
            get
            {
                return ResourceManager.GetString("RequiredSupplier", resourceCulture);
            }
        }

        internal static string RequiredImage
        {
            get
            {
                return ResourceManager.GetString("RequiredImage", resourceCulture);
            }
        }

        internal static string RequireNameVn
        {
            get
            {
                return ResourceManager.GetString("RequireNameVn", resourceCulture);
            }
        }

        internal static string RequireName
        {
            get
            {
                return ResourceManager.GetString("RequireName", resourceCulture);
            }
        }

        internal static string EmailInvalid
        {
            get
            {
                return ResourceManager.GetString("EmailInvalid", resourceCulture);
            }
        }

        internal static string UserInvalid
        {
            get
            {
                return ResourceManager.GetString("UserInvalid", resourceCulture);
            }
        }

        internal static string MaxLengthUsername
        {
            get
            {
                return ResourceManager.GetString("MaxLengthUsername", resourceCulture);
            }
        }

        internal static string RequiredSupplierName
        {
            get
            {
                return ResourceManager.GetString("RequiredSupplierName", resourceCulture);
            }
        }

        internal static string MaxLengthSupplierName
        {
            get
            {
                return ResourceManager.GetString("MaxLengthSupplierName", resourceCulture);
            }
        }

        internal static string RequiredSupplierEmail
        {
            get
            {
                return ResourceManager.GetString("RequiredSupplierEmail", resourceCulture);
            }
        }

        internal static string MaxLengthSupplerEmail
        {
            get
            {
                return ResourceManager.GetString("MaxLengthSupplerEmail", resourceCulture);
            }
        }

        internal static string OrderViewModelRequiredName
        {
            get
            {
                return ResourceManager.GetString("OrderViewModelRequiredName", resourceCulture);
            }
        }

        internal static string OrderViewModelRequiredCity
        {
            get
            {
                return ResourceManager.GetString("OrderViewModelRequiredCity", resourceCulture);
            }
        }

        internal static string EditCategoryViewModelMaxLengthDescription
        {
            get
            {
                return ResourceManager.GetString("EditCategoryViewModelMaxLengthDescription", resourceCulture);
            }
        }

        internal static string RangeQuantity
        {
            get
            {
                return ResourceManager.GetString("RangeQuantity", resourceCulture);
            }
        }

        internal static string MaxLengthPhone
        {
            get
            {
                return ResourceManager.GetString("MaxLengthPhone", resourceCulture);
            }
        }

        internal static string MaxLengthAddress
        {
            get
            {
                return ResourceManager.GetString("MaxLengthAddress", resourceCulture);
            }
        }

        internal static string MaxLengthEmail
        {
            get
            {
                return ResourceManager.GetString("MaxLengthEmail", resourceCulture);
            }
        }

        public static string MaxLengthFirstName
        {
            get
            {
                return ResourceManager.GetString("MaxLengthFistName");
            }
        }

        public static string MaxLengthLastName
        {
            get
            {
                return ResourceManager.GetString("MaxLengthLastName");
            }
        }

        public static string MaxLengthFullname
        {
            get
            {
                return ResourceManager.GetString("MaxLengthFullName");
            }
        }
    }
}
